services:
  search-api:
    build:
      context: .
      dockerfile: services/search_api/Dockerfile
    container_name: search-api
    ports:
      - "8000:8000"
    environment:
      POKE_API_URL: http://poke-api:8001
      POKE_STATS_URL: http://poke-stats:8002
      POKE_IMAGES_URL: http://poke-images:8003
      LOG_DB_PATH: /app/data/central_logs.db
    volumes:
      - ./data:/app/data
    depends_on:
      - poke-api
      - poke-stats
      - poke-images

  poke-api:
    build:
      context: .
      dockerfile: services/poke_api/Dockerfile
    container_name: poke-api
    ports:
      - "8001:8001"
    environment:
      ERROR_RATE: "0.08"
      LOG_DB_PATH: /app/data/central_logs.db
    volumes:
      - ./data:/app/data

  poke-stats:
    build:
      context: .
      dockerfile: services/poke_stats/Dockerfile
    container_name: poke-stats
    ports:
      - "8002:8002"
    environment:
      ERROR_RATE: "0.05"
      LOG_DB_PATH: /app/data/central_logs.db
    volumes:
      - ./data:/app/data

  poke-images:
    build:
      context: .
      dockerfile: services/poke_images/Dockerfile
    container_name: poke-images
    ports:
      - "8003:8003"
    environment:
      ERROR_RATE: "0.10"
      LOG_DB_PATH: /app/data/central_logs.db
    volumes:
      - ./data:/app/data
